# Generated by Django 5.2.4 on 2025-07-06 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_key', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='Session Id')),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True, verbose_name='User-Agent')),
                ('ip', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ip')),
                ('last_visit', models.DateTimeField(auto_now=True, verbose_name='Дата последнего посещения')),
            ],
        ),
        migrations.AlterField(
            model_name='collection',
            name='items',
            field=models.ManyToManyField(through='main.ItemCollection', to='main.item', verbose_name='Товары'),
        ),
        migrations.AlterField(
            model_name='collectionimage',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.collection', verbose_name='Коллекция'),
        ),
        migrations.AlterField(
            model_name='itemcollection',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.item', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.item', verbose_name='Товар'),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1, verbose_name='Колличество')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.item', verbose_name='Товар')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.session', verbose_name='Пользователь(сессия)')),
            ],
        ),
    ]
